/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MenusRouteImport } from './routes/menus'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ApiPublicPosOrdersRouteImport } from './routes/api/public/pos/orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusRoute = MenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPosOrdersRoute = ApiPublicPosOrdersRouteImport.update({
  id: '/api/public/pos/orders',
  path: '/api/public/pos/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/media': typeof MediaRoute
  '/menus': typeof MenusRoute
  '/overview': typeof OverviewRoute
  '/playlists': typeof PlaylistsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/schedules': typeof SchedulesRoute
  '/screens': typeof ScreensRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/public/pos/orders': typeof ApiPublicPosOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/media': typeof MediaRoute
  '/menus': typeof MenusRoute
  '/overview': typeof OverviewRoute
  '/playlists': typeof PlaylistsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/schedules': typeof SchedulesRoute
  '/screens': typeof ScreensRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/public/pos/orders': typeof ApiPublicPosOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/media': typeof MediaRoute
  '/menus': typeof MenusRoute
  '/overview': typeof OverviewRoute
  '/playlists': typeof PlaylistsRoute
  '/queue': typeof QueueRoute
  '/reports': typeof ReportsRoute
  '/schedules': typeof SchedulesRoute
  '/screens': typeof ScreensRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/public/pos/orders': typeof ApiPublicPosOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/approvals'
    | '/audit'
    | '/campaigns'
    | '/company'
    | '/dashboard'
    | '/insights'
    | '/media'
    | '/menus'
    | '/overview'
    | '/playlists'
    | '/queue'
    | '/reports'
    | '/schedules'
    | '/screens'
    | '/templates'
    | '/users'
    | '/api/public/pos/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/approvals'
    | '/audit'
    | '/campaigns'
    | '/company'
    | '/dashboard'
    | '/insights'
    | '/media'
    | '/menus'
    | '/overview'
    | '/playlists'
    | '/queue'
    | '/reports'
    | '/schedules'
    | '/screens'
    | '/templates'
    | '/users'
    | '/api/public/pos/orders'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/approvals'
    | '/audit'
    | '/campaigns'
    | '/company'
    | '/dashboard'
    | '/insights'
    | '/media'
    | '/menus'
    | '/overview'
    | '/playlists'
    | '/queue'
    | '/reports'
    | '/schedules'
    | '/screens'
    | '/templates'
    | '/users'
    | '/api/public/pos/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  CampaignsRoute: typeof CampaignsRoute
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  MediaRoute: typeof MediaRoute
  MenusRoute: typeof MenusRoute
  OverviewRoute: typeof OverviewRoute
  PlaylistsRoute: typeof PlaylistsRoute
  QueueRoute: typeof QueueRoute
  ReportsRoute: typeof ReportsRoute
  SchedulesRoute: typeof SchedulesRoute
  ScreensRoute: typeof ScreensRoute
  TemplatesRoute: typeof TemplatesRoute
  UsersRoute: typeof UsersRoute
  ApiPublicPosOrdersRoute: typeof ApiPublicPosOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus': {
      id: '/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pos/orders': {
      id: '/api/public/pos/orders'
      path: '/api/public/pos/orders'
      fullPath: '/api/public/pos/orders'
      preLoaderRoute: typeof ApiPublicPosOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  CampaignsRoute: CampaignsRoute,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  MediaRoute: MediaRoute,
  MenusRoute: MenusRoute,
  OverviewRoute: OverviewRoute,
  PlaylistsRoute: PlaylistsRoute,
  QueueRoute: QueueRoute,
  ReportsRoute: ReportsRoute,
  SchedulesRoute: SchedulesRoute,
  ScreensRoute: ScreensRoute,
  TemplatesRoute: TemplatesRoute,
  UsersRoute: UsersRoute,
  ApiPublicPosOrdersRoute: ApiPublicPosOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
